In [1]:
# import libraries

import numpy as np
import pandas as pd
from collections import Counter
import re

In [2]:
df_afn = pd.read_csv('src/afn/us_sentiments_analysis.csv')
df_afn

,date,sentiment_us,AL,AK,AZ,AR,CA,CO,CT,DE,...,SD,TN,TX,UT,VT,VA,WA,WV,WI,WY
0,1/22/20,-0.229980,0.333333,0.200000,0.276596,0.045455,0.270181,0.240000,0.292683,0.272727,...,0.222222,0.243902,0.254042,0.277778,0.142857,0.272000,0.309524,0.307692,0.179104,0.000000
1,1/23/20,-0.471438,0.170543,0.185714,0.138686,0.163522,0.158777,0.174312,0.186441,0.221154,...,0.121951,0.182390,0.180490,0.142857,0.200000,0.194175,0.190878,0.217822,0.130952,0.215686
2,1/24/20,-0.206374,0.267898,0.296804,0.241701,0.281796,0.302619,0.227036,0.247039,0.244604,...,0.180328,0.229655,0.335515,0.269113,0.172727,0.253559,0.248660,0.249097,0.204969,0.184713
3,1/25/20,-0.296810,0.201597,0.195946,0.219903,0.207243,0.262903,0.225731,0.198483,0.189873,...,0.174026,0.190509,0.243462,0.232941,0.316327,0.213348,0.223044,0.210526,0.211750,0.152778
4,1/26/20,-0.249704,0.188785,0.208054,0.165341,0.194991,0.245768,0.216264,0.220805,0.260204,...,0.160656,0.215480,0.215494,0.219231,0.285714,0.196863,0.230094,0.163690,0.188447,0.217054
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,5/04/20,-0.163468,0.266369,0.289398,0.257224,0.270710,0.281416,0.286913,0.288043,0.251412,...,0.344156,0.267892,0.281807,0.319572,0.290749,0.289427,0.308294,0.321348,0.276489,0.175676
103,5/05/20,-0.169094,0.291436,0.301325,0.273917,0.251830,0.273937,0.285714,0.277567,0.279006,...,0.243243,0.294958,0.267616,0.309013,0.298450,0.291103,0.312089,0.294624,0.293509,0.289655
104,5/06/20,-0.160915,0.276625,0.270440,0.281277,0.271341,0.284240,0.292874,0.287829,0.289277,...,0.333333,0.289049,0.280033,0.317935,0.260223,0.297369,0.314625,0.303797,0.307077,0.258621
105,5/07/20,-0.132329,0.304676,0.241042,0.287765,0.316188,0.309104,0.297524,0.316565,0.311688,...,0.244444,0.323278,0.296583,0.352723,0.363636,0.331547,0.326400,0.313636,0.309629,0.371257
106,5/08/20,-0.119723,0.324607,0.284000,0.288123,0.290718,0.306142,0.311348,0.327853,0.291815,...,0.304000,0.307042,0.293762,0.359511,0.342105,0.337651,0.331942,0.344411,0.311094,0.257576

In [3]:
df_textblob = pd.read_csv('src/textblob/us_sentiments_analysis.csv')
df_textblob

,date,sentiment_us,AL,AK,AZ,AR,CA,CO,CT,DE,...,SD,TN,TX,UT,VT,VA,WA,WV,WI,WY
0,1/22/20,0.416963,0.571429,0.466667,0.531915,0.590909,0.551895,0.592000,0.731707,0.500000,...,0.222222,0.621951,0.642032,0.555556,0.714286,0.624000,0.627706,0.653846,0.597015,1.000000
1,1/23/20,0.194959,0.387597,0.414286,0.397810,0.433962,0.446633,0.483945,0.423729,0.451923,...,0.475610,0.423480,0.403361,0.385714,0.450000,0.432039,0.497185,0.415842,0.388889,0.352941
2,1/24/20,0.252480,0.461894,0.438356,0.447874,0.468828,0.433366,0.471404,0.450085,0.424460,...,0.422131,0.475862,0.408256,0.486239,0.445455,0.470508,0.500383,0.451264,0.484472,0.484076
3,1/25/20,0.206506,0.423154,0.469595,0.415049,0.438632,0.412881,0.452632,0.417193,0.411392,...,0.477922,0.400275,0.386205,0.463529,0.500000,0.434902,0.470181,0.396491,0.430845,0.388889
4,1/26/20,0.203046,0.429907,0.369128,0.492044,0.416816,0.484934,0.440778,0.453386,0.474490,...,0.445902,0.430960,0.364244,0.394231,0.517857,0.395378,0.449980,0.443452,0.388258,0.434109
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,5/04/20,0.134251,0.382440,0.441261,0.392902,0.378698,0.409676,0.419044,0.397645,0.392655,...,0.415584,0.406190,0.411529,0.431193,0.422907,0.414026,0.433664,0.411236,0.411285,0.304054
103,5/05/20,0.179961,0.426796,0.433775,0.428031,0.453880,0.422924,0.431746,0.453232,0.367403,...,0.405405,0.432842,0.409506,0.426323,0.422481,0.424565,0.441323,0.430108,0.412981,0.413793
104,5/06/20,0.164068,0.403873,0.383648,0.428157,0.413110,0.414895,0.419342,0.414474,0.438903,...,0.451852,0.415535,0.410831,0.404891,0.420074,0.424908,0.446008,0.426160,0.426462,0.419540
105,5/07/20,0.174728,0.441931,0.335505,0.436434,0.438729,0.436690,0.430511,0.423244,0.444805,...,0.466667,0.431337,0.420042,0.443069,0.463203,0.448017,0.443680,0.456818,0.431089,0.389222
106,5/08/20,0.187647,0.436300,0.452000,0.452490,0.448336,0.439498,0.423860,0.433269,0.416370,...,0.384000,0.440563,0.428100,0.464223,0.456140,0.460510,0.457701,0.459215,0.442279,0.378788

In [4]:
df_vader = pd.read_csv('src/vader/us_sentiments_analysis.csv')
df_vader

,date,sentiment_us,AL,AK,AZ,AR,CA,CO,CT,DE,...,SD,TN,TX,UT,VT,VA,WA,WV,WI,WY
0,1/22/20,-0.052268,0.380952,0.400000,0.329787,0.181818,0.317957,0.336000,0.317073,0.454545,...,0.222222,0.317073,0.297921,0.277778,0.285714,0.376000,0.370130,0.230769,0.283582,0.000000
1,1/23/20,-0.264139,0.271318,0.271429,0.213504,0.226415,0.253161,0.261468,0.296610,0.336538,...,0.182927,0.253669,0.251005,0.278571,0.200000,0.279935,0.274775,0.257426,0.190476,0.333333
2,1/24/20,0.007633,0.339492,0.356164,0.338963,0.331671,0.385674,0.319757,0.331641,0.374101,...,0.286885,0.322759,0.384396,0.339450,0.309091,0.341695,0.344907,0.317690,0.293168,0.280255
3,1/25/20,-0.056723,0.277445,0.270270,0.300485,0.275654,0.358670,0.301170,0.278129,0.265823,...,0.257143,0.266850,0.328908,0.320000,0.397959,0.296499,0.304866,0.280702,0.291310,0.236111
4,1/26/20,-0.090386,0.272897,0.297539,0.212829,0.270125,0.293817,0.295227,0.292444,0.331633,...,0.245902,0.278638,0.271512,0.282692,0.375000,0.273628,0.305022,0.229167,0.247159,0.232558
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,5/04/20,-0.048433,0.358631,0.352436,0.322550,0.359467,0.340177,0.351091,0.338768,0.327684,...,0.422078,0.344294,0.339451,0.371560,0.312775,0.347455,0.367414,0.361798,0.334796,0.263514
103,5/05/20,-0.034457,0.378453,0.367550,0.355627,0.348463,0.343067,0.359127,0.353612,0.353591,...,0.324324,0.370817,0.340450,0.356223,0.410853,0.360413,0.380318,0.378495,0.367030,0.386207
104,5/06/20,-0.044504,0.348548,0.345912,0.333527,0.317073,0.348173,0.357087,0.342928,0.354115,...,0.377778,0.337012,0.349814,0.376359,0.330855,0.358974,0.384506,0.322785,0.369231,0.344828
105,5/07/20,-0.020378,0.333333,0.302932,0.349985,0.375189,0.372414,0.361422,0.384215,0.344156,...,0.362963,0.382710,0.353646,0.410891,0.380952,0.379421,0.392800,0.381818,0.374449,0.461078
106,5/08/20,-0.011160,0.357766,0.332000,0.353257,0.323993,0.361860,0.363725,0.378143,0.327402,...,0.376000,0.364507,0.353944,0.418848,0.381579,0.391559,0.383536,0.389728,0.378561,0.295455

In [5]:
df_ensemble = pd.read_csv('src/ensemble/us_sentiments_analysis.csv')
df_ensemble

,date,sentiment_us,AL,AK,AZ,AR,CA,CO,CT,DE,...,SD,TN,TX,UT,VT,VA,WA,WV,WI,WY
0,1/22/20,-0.168639,0.333333,0.266667,0.276596,0.136364,0.293245,0.296000,0.341463,0.363636,...,0.222222,0.231707,0.277136,0.277778,0.142857,0.344000,0.333333,0.192308,0.238806,0.000000
1,1/23/20,-0.404321,0.209302,0.242857,0.167883,0.169811,0.186416,0.194954,0.216102,0.278846,...,0.146341,0.194969,0.211911,0.200000,0.200000,0.226537,0.222973,0.227723,0.130952,0.235294
2,1/24/20,-0.134307,0.297921,0.333333,0.287129,0.296758,0.337713,0.264298,0.282572,0.309353,...,0.213115,0.263448,0.351668,0.327217,0.227273,0.292881,0.296911,0.281588,0.233540,0.235669
3,1/25/20,-0.220988,0.231537,0.226351,0.238350,0.223340,0.295247,0.240351,0.225032,0.215190,...,0.189610,0.214580,0.271312,0.272941,0.336735,0.247265,0.250954,0.231579,0.230110,0.173611
4,1/26/20,-0.197991,0.209346,0.237136,0.180507,0.218247,0.261350,0.251621,0.252208,0.301020,...,0.200000,0.237152,0.235047,0.242308,0.315476,0.222452,0.260310,0.199405,0.195076,0.224806
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,5/04/20,-0.106193,0.303571,0.323782,0.287688,0.315089,0.310265,0.310403,0.308877,0.290960,...,0.370130,0.301741,0.303100,0.337920,0.308370,0.321111,0.337854,0.328090,0.297806,0.182432
103,5/05/20,-0.105504,0.341160,0.327815,0.314045,0.292826,0.305835,0.315079,0.311027,0.303867,...,0.270270,0.327532,0.299859,0.339056,0.372093,0.318182,0.351742,0.326882,0.340609,0.324138
104,5/06/20,-0.101089,0.318119,0.317610,0.318142,0.291159,0.320279,0.330070,0.306743,0.319202,...,0.362963,0.306027,0.319140,0.339674,0.301115,0.330003,0.346877,0.322785,0.339077,0.293103
105,5/07/20,-0.079519,0.313725,0.273616,0.318576,0.344932,0.340077,0.329872,0.351258,0.347403,...,0.274074,0.360198,0.325467,0.379950,0.363636,0.353698,0.359840,0.352273,0.336690,0.461078
106,5/08/20,-0.063271,0.329843,0.316000,0.321456,0.313485,0.333220,0.334142,0.361702,0.323843,...,0.376000,0.340282,0.325448,0.392670,0.377193,0.368993,0.359636,0.353474,0.346327,0.287879

In [6]:
df_corr = pd.read_csv('src/us_correlation_analysis.csv')
df_corr

        date    tweets    cases  cases_daily  tweets_daily
0    1/22/20      5070        1            1          5070
1    1/23/20     29788        1            0         24718
2    1/24/20    104594        2            1         74806
3    1/25/20    189463        2            0         84869
4    1/26/20    297655        5            3        108192
..       ...       ...      ...          ...           ...
102   5/4/20  13601803  1180375        22335        115686
103   5/5/20  13724102  1204351        23976        122299
104   5/6/20  13848764  1229331        24980        124662
105   5/7/20  13967566  1257023        27692        118802
106   5/8/20  14067296  1283929        26906         99730

[107 rows x 5 columns]

In [7]:
df_all = df_corr[['date', 'cases_daily', 'tweets_daily']]
df_all

        date  cases_daily  tweets_daily
0    1/22/20            1          5070
1    1/23/20            0         24718
2    1/24/20            1         74806
3    1/25/20            0         84869
4    1/26/20            3        108192
..       ...          ...           ...
102   5/4/20        22335        115686
103   5/5/20        23976        122299
104   5/6/20        24980        124662
105   5/7/20        27692        118802
106   5/8/20        26906         99730

[107 rows x 3 columns]

In [8]:
df_all['cases_total'] = df_corr['cases']
df_all['tweets_total'] = df_corr['tweets']
df_all

/Users/allen/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

        date  cases_daily  tweets_daily  cases_total  tweets_total
0    1/22/20            1          5070            1          5070
1    1/23/20            0         24718            1         29788
2    1/24/20            1         74806            2        104594
3    1/25/20            0         84869            2        189463
4    1/26/20            3        108192            5        297655
..       ...          ...           ...          ...           ...
102   5/4/20        22335        115686      1180375      13601803
103   5/5/20        23976        122299      1204351      13724102
104   5/6/20        24980        124662      1229331      13848764
105   5/7/20        27692        118802      1257023      13967566
106   5/8/20        26906         99730      1283929      14067296

[107 rows x 5 columns]

In [9]:
df_all['sentiment_afn'] = df_afn['sentiment_us']
df_all['sentiment_ensemble'] = df_ensemble['sentiment_us']
df_all['sentiment_textblob'] = df_textblob['sentiment_us']
df_all['sentiment_vader'] = df_vader['sentiment_us']
df_all

,date,cases_daily,tweets_daily,cases_total,tweets_total,sentiment_afn,sentiment_ensemble,sentiment_textblob,sentiment_vader
0,1/22/20,1,5070,1,5070,-0.229980,-0.168639,0.416963,-0.052268
1,1/23/20,0,24718,1,29788,-0.471438,-0.404321,0.194959,-0.264139
2,1/24/20,1,74806,2,104594,-0.206374,-0.134307,0.252480,0.007633
3,1/25/20,0,84869,2,189463,-0.296810,-0.220988,0.206506,-0.056723
4,1/26/20,3,108192,5,297655,-0.249704,-0.197991,0.203046,-0.090386
...,...,...,...,...,...,...,...,...,...
102,5/4/20,22335,115686,1180375,13601803,-0.163468,-0.106193,0.134251,-0.048433
103,5/5/20,23976,122299,1204351,13724102,-0.169094,-0.105504,0.179961,-0.034457
104,5/6/20,24980,124662,1229331,13848764,-0.160915,-0.101089,0.164068,-0.044504
105,5/7/20,27692,118802,1257023,13967566,-0.132329,-0.079519,0.174728,-0.020378
106,5/8/20,26906,99730,1283929,14067296,-0.119723,-0.063271,0.187647,-0.011160

In [10]:
df_all.to_csv('src/us_sentiment_models.csv')